# Load Quartus II Tcl Project package
package require ::quartus::project

set need_to_close_project 0
set make_assignments 1


set make_assignments 1

set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[9]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[10]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[11]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[12]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[13]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[14]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[15]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[16]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[17]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[18]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[19]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[20]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[21]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[22]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[23]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[24]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[25]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[26]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[27]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[28]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[29]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[30]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[31]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[32]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[33]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[34]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO0[35]

set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[9]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[10]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[11]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[12]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[13]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[14]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[15]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[16]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[17]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[18]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[19]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[20]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[21]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[22]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[23]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[24]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[25]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[26]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[27]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[28]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[29]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[30]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[31]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[32]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[33]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[34]
set_instance_assignment -name IO_STANDARD "2.5 V" -to GPIO1[35]

set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n8
set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p8
set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n8
set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p8


set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clk_in0
set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clk_out0

set_instance_assignment -name IO_STANDARD HCSL -to hsmc_ref_clk_n
set_instance_assignment -name IO_STANDARD HCSL -to hsmc_ref_clk_p

set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_scl
set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_sda

# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkin_n[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkin_n[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkin_p[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkin_p[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkout_n[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkout_n[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkout_p[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clkout_p[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clk_in0
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_clk_out0
#
# set_instance_assignment -name IO_STANDARD HCSL -to hsmc_ref_clk_n
# set_instance_assignment -name IO_STANDARD HCSL -to hsmc_ref_clk_p
#
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[0]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[3]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[4]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[5]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[6]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[7]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[8]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[9]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[10]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[11]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[12]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[13]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[14]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[15]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_n[16]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[0]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[3]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[4]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[5]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[6]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[7]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[8]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[9]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[10]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[11]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[12]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[13]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[14]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[15]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_rx_p[16]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_scl
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_sda
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[0]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[3]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[4]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[5]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[6]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[7]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[8]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[9]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[10]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[11]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[12]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[13]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[14]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[15]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_n[16]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[0]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[1]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[2]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[3]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[4]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[5]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[6]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[7]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[8]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[9]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[10]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[11]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[12]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[13]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[14]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[15]
# set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmc_tx_p[16]

set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[0]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[1]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[2]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[3]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[4]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[5]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[6]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_n[7]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[0]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[1]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[2]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[3]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[4]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[5]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[6]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_rx_p[7]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[0]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[1]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[2]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[3]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[4]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[5]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[6]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_n[7]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[0]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[1]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[2]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[3]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[4]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[5]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[6]
set_instance_assignment -name IO_STANDARD "1.5-V PCML" -to hsmc_gxb_tx_p[7]

set_location_assignment PIN_G15 -to GPIO0[0]
set_location_assignment PIN_F14 -to GPIO0[1]
set_location_assignment PIN_H15 -to GPIO0[2]
set_location_assignment PIN_F15 -to GPIO0[3]
set_location_assignment PIN_A13 -to GPIO0[4]
set_location_assignment PIN_G13 -to GPIO0[5]
set_location_assignment PIN_B13 -to GPIO0[6]
set_location_assignment PIN_H14 -to GPIO0[7]
set_location_assignment PIN_B11 -to GPIO0[8]
set_location_assignment PIN_E13 -to GPIO0[9]
set_location_assignment PIN_C12 -to GPIO0[10]
set_location_assignment PIN_F13 -to GPIO0[11]
set_location_assignment PIN_B8 -to GPIO0[12]
set_location_assignment PIN_B12 -to GPIO0[13]
set_location_assignment PIN_C8 -to GPIO0[14]
set_location_assignment PIN_C13 -to GPIO0[15]
set_location_assignment PIN_A10 -to GPIO0[16]
set_location_assignment PIN_D10 -to GPIO0[17]
set_location_assignment PIN_A11 -to GPIO0[18]
set_location_assignment PIN_D11 -to GPIO0[19]
set_location_assignment PIN_B7 -to GPIO0[20]
set_location_assignment PIN_D12 -to GPIO0[21]
set_location_assignment PIN_C7 -to GPIO0[22]
set_location_assignment PIN_E12 -to GPIO0[23]
set_location_assignment PIN_A5 -to GPIO0[24]
set_location_assignment PIN_D9 -to GPIO0[25]
set_location_assignment PIN_A6 -to GPIO0[26]
set_location_assignment PIN_E9 -to GPIO0[27]
set_location_assignment PIN_A3 -to GPIO0[28]
set_location_assignment PIN_B5 -to GPIO0[29]
set_location_assignment PIN_A4 -to GPIO0[30]
set_location_assignment PIN_B6 -to GPIO0[31]
set_location_assignment PIN_B2 -to GPIO0[32]
set_location_assignment PIN_C2 -to GPIO0[33]
set_location_assignment PIN_B1 -to GPIO0[34]
set_location_assignment PIN_D2 -to GPIO0[35]

set_location_assignment PIN_AB27 -to GPIO1[0]
set_location_assignment PIN_F8 -to GPIO1[1]
set_location_assignment PIN_AA26 -to GPIO1[2]
set_location_assignment PIN_F9 -to GPIO1[3]
set_location_assignment PIN_B3 -to GPIO1[4]
set_location_assignment PIN_G8 -to GPIO1[5]
set_location_assignment PIN_C3 -to GPIO1[6]
set_location_assignment PIN_H8 -to GPIO1[7]
set_location_assignment PIN_D4 -to GPIO1[8]
set_location_assignment PIN_H7 -to GPIO1[9]
set_location_assignment PIN_E4 -to GPIO1[10]
set_location_assignment PIN_J7 -to GPIO1[11]
set_location_assignment PIN_E2 -to GPIO1[12]
set_location_assignment PIN_K8 -to GPIO1[13]
set_location_assignment PIN_E3 -to GPIO1[14]
set_location_assignment PIN_K7 -to GPIO1[15]
set_location_assignment PIN_E6 -to GPIO1[16]
set_location_assignment PIN_J9 -to GPIO1[17]
set_location_assignment PIN_E7 -to GPIO1[18]
set_location_assignment PIN_J10 -to GPIO1[19]
set_location_assignment PIN_C4 -to GPIO1[20]
set_location_assignment PIN_F10 -to GPIO1[21]
set_location_assignment PIN_D5 -to GPIO1[22]
set_location_assignment PIN_G10 -to GPIO1[23]
set_location_assignment PIN_C5 -to GPIO1[24]
set_location_assignment PIN_J12 -to GPIO1[25]
set_location_assignment PIN_D6 -to GPIO1[26]
set_location_assignment PIN_K12 -to GPIO1[27]
set_location_assignment PIN_F6 -to GPIO1[28]
set_location_assignment PIN_G11 -to GPIO1[29]
set_location_assignment PIN_G7 -to GPIO1[30]
set_location_assignment PIN_G12 -to GPIO1[31]
set_location_assignment PIN_D7 -to GPIO1[32]
set_location_assignment PIN_A8 -to GPIO1[33]
set_location_assignment PIN_E8 -to GPIO1[34]
set_location_assignment PIN_A9 -to GPIO1[35]

set_location_assignment PIN_D1 -to hsmc_tx_n8
set_location_assignment PIN_E1 -to hsmc_tx_p8
set_location_assignment PIN_E11 -to hsmc_rx_n8
set_location_assignment PIN_F11 -to hsmc_rx_p8

set_location_assignment PIN_C10 -to hsmc_d[0]
set_location_assignment PIN_C9 -to hsmc_d[2]
set_location_assignment PIN_H13 -to hsmc_d[1]
set_location_assignment PIN_H12 -to hsmc_d[3]

set_location_assignment PIN_J14 -to hsmc_clk_in0
set_location_assignment PIN_AD29 -to hsmc_clk_out0


set_location_assignment PIN_AA28 -to hsmc_scl
set_location_assignment PIN_AE29 -to hsmc_sda

# set_location_assignment PIN_AB27 -to hsmc_clkin_n[1]
# set_location_assignment PIN_AA26 -to hsmc_clkin_p[1]
# set_location_assignment PIN_G15 -to hsmc_clkin_n[2]
# set_location_assignment PIN_H15 -to hsmc_clkin_p[2]
# set_location_assignment PIN_E6 -to hsmc_clkout_n[1]
# set_location_assignment PIN_E7 -to hsmc_clkout_p[1]
# set_location_assignment PIN_A10 -to hsmc_clkout_n[2]
# set_location_assignment PIN_A11 -to hsmc_clkout_p[2]
# set_location_assignment PIN_J14 -to hsmc_clk_in0
# set_location_assignment PIN_AD29 -to hsmc_clk_out0
#
#
# set_location_assignment PIN_AE1 -to hsmc_gxb_rx_n[0]
# set_location_assignment PIN_AC1 -to hsmc_gxb_rx_n[1]
# set_location_assignment PIN_AA1 -to hsmc_gxb_rx_n[2]
# set_location_assignment PIN_W1 -to hsmc_gxb_rx_n[3]
# set_location_assignment PIN_U1 -to hsmc_gxb_rx_n[4]
# set_location_assignment PIN_R1 -to hsmc_gxb_rx_n[5]
# set_location_assignment PIN_N1 -to hsmc_gxb_rx_n[6]
# set_location_assignment PIN_L1 -to hsmc_gxb_rx_n[7]
# set_location_assignment PIN_AE2 -to hsmc_gxb_rx_p[0]
# set_location_assignment PIN_AC2 -to hsmc_gxb_rx_p[1]
# set_location_assignment PIN_AA2 -to hsmc_gxb_rx_p[2]
# set_location_assignment PIN_W2 -to hsmc_gxb_rx_p[3]
# set_location_assignment PIN_U2 -to hsmc_gxb_rx_p[4]
# set_location_assignment PIN_R2 -to hsmc_gxb_rx_p[5]
# set_location_assignment PIN_N2 -to hsmc_gxb_rx_p[6]
# set_location_assignment PIN_L2 -to hsmc_gxb_rx_p[7]
# set_location_assignment PIN_AD3 -to hsmc_gxb_tx_n[0]
# set_location_assignment PIN_AB3 -to hsmc_gxb_tx_n[1]
# set_location_assignment PIN_Y3 -to hsmc_gxb_tx_n[2]
# set_location_assignment PIN_V3 -to hsmc_gxb_tx_n[3]
# set_location_assignment PIN_T3 -to hsmc_gxb_tx_n[4]
# set_location_assignment PIN_P3 -to hsmc_gxb_tx_n[5]
# set_location_assignment PIN_M3 -to hsmc_gxb_tx_n[6]
# set_location_assignment PIN_K3 -to hsmc_gxb_tx_n[7]
# set_location_assignment PIN_AD4 -to hsmc_gxb_tx_p[0]
# set_location_assignment PIN_AB4 -to hsmc_gxb_tx_p[1]
# set_location_assignment PIN_Y4 -to hsmc_gxb_tx_p[2]
# set_location_assignment PIN_V4 -to hsmc_gxb_tx_p[3]
# set_location_assignment PIN_T4 -to hsmc_gxb_tx_p[4]
# set_location_assignment PIN_P4 -to hsmc_gxb_tx_p[5]
# set_location_assignment PIN_M4 -to hsmc_gxb_tx_p[6]
# set_location_assignment PIN_K4 -to hsmc_gxb_tx_p[7]
# set_location_assignment PIN_W7 -to hsmc_ref_clk_n
# set_location_assignment PIN_W8 -to hsmc_ref_clk_p
#
# set_location_assignment PIN_G12 -to hsmc_rx_p[0]
# set_location_assignment PIN_G11 -to hsmc_rx_n[0]
# set_location_assignment PIN_K12 -to hsmc_rx_p[1]
# set_location_assignment PIN_J12 -to hsmc_rx_n[1]
# set_location_assignment PIN_G10 -to hsmc_rx_p[2]
# set_location_assignment PIN_F10 -to hsmc_rx_n[2]
# set_location_assignment PIN_J10 -to hsmc_rx_p[3]
# set_location_assignment PIN_J9 -to hsmc_rx_n[3]
# set_location_assignment PIN_K7 -to hsmc_rx_p[4]
# set_location_assignment PIN_K8 -to hsmc_rx_n[4]
# set_location_assignment PIN_J7 -to hsmc_rx_p[5]
# set_location_assignment PIN_H7 -to hsmc_rx_n[5]
# set_location_assignment PIN_H8 -to hsmc_rx_p[6]
# set_location_assignment PIN_G8 -to hsmc_rx_n[6]
# set_location_assignment PIN_F9 -to hsmc_rx_p[7]
# set_location_assignment PIN_F8 -to hsmc_rx_n[7]
# set_location_assignment PIN_F11 -to hsmc_rx_p[8]
# set_location_assignment PIN_E11 -to hsmc_rx_n[8]
# set_location_assignment PIN_B6 -to hsmc_rx_p[9]
# set_location_assignment PIN_B5 -to hsmc_rx_n[9]
# set_location_assignment PIN_E9 -to hsmc_rx_p[10]
# set_location_assignment PIN_D9 -to hsmc_rx_n[10]
# set_location_assignment PIN_E12 -to hsmc_rx_p[11]
# set_location_assignment PIN_D12 -to hsmc_rx_n[11]
# set_location_assignment PIN_D11 -to hsmc_rx_p[12]
# set_location_assignment PIN_D10 -to hsmc_rx_n[12]
# set_location_assignment PIN_C13 -to hsmc_rx_p[13]
# set_location_assignment PIN_B12 -to hsmc_rx_n[13]
# set_location_assignment PIN_F13 -to hsmc_rx_p[14]
# set_location_assignment PIN_E13 -to hsmc_rx_n[14]
# set_location_assignment PIN_H14 -to hsmc_rx_p[15]
# set_location_assignment PIN_G13 -to hsmc_rx_n[15]
# set_location_assignment PIN_F15 -to hsmc_rx_p[16]
# set_location_assignment PIN_F14 -to hsmc_rx_n[16]
#
#
# set_location_assignment PIN_A9 -to hsmc_tx_p[0]
# set_location_assignment PIN_A8 -to hsmc_tx_n[0]
# set_location_assignment PIN_E8 -to hsmc_tx_p[1]
# set_location_assignment PIN_D7 -to hsmc_tx_n[1]
# set_location_assignment PIN_G7 -to hsmc_tx_p[2]
# set_location_assignment PIN_F6 -to hsmc_tx_n[2]
# set_location_assignment PIN_D6 -to hsmc_tx_p[3]
# set_location_assignment PIN_C5 -to hsmc_tx_n[3]
# set_location_assignment PIN_D5 -to hsmc_tx_p[4]
# set_location_assignment PIN_C4 -to hsmc_tx_n[4]
# set_location_assignment PIN_E3 -to hsmc_tx_p[5]
# set_location_assignment PIN_E2 -to hsmc_tx_n[5]
# set_location_assignment PIN_E4 -to hsmc_tx_p[6]
# set_location_assignment PIN_D4 -to hsmc_tx_n[6]
# set_location_assignment PIN_C3 -to hsmc_tx_p[7]
# set_location_assignment PIN_B3 -to hsmc_tx_n[7]
# set_location_assignment PIN_D1 -to hsmc_tx_n[8]
# set_location_assignment PIN_E1 -to hsmc_tx_p[8]
# set_location_assignment PIN_D2 -to hsmc_tx_p[9]
# set_location_assignment PIN_C2 -to hsmc_tx_n[9]
# set_location_assignment PIN_B1 -to hsmc_tx_p[10]
# set_location_assignment PIN_B2 -to hsmc_tx_n[10]
# set_location_assignment PIN_A4 -to hsmc_tx_p[11]
# set_location_assignment PIN_A3 -to hsmc_tx_n[11]
# set_location_assignment PIN_A6 -to hsmc_tx_p[12]
# set_location_assignment PIN_A5 -to hsmc_tx_n[12]
# set_location_assignment PIN_C7 -to hsmc_tx_p[13]
# set_location_assignment PIN_B7 -to hsmc_tx_n[13]
# set_location_assignment PIN_C8 -to hsmc_tx_p[14]
# set_location_assignment PIN_B8 -to hsmc_tx_n[14]
# set_location_assignment PIN_C12 -to hsmc_tx_p[15]
# set_location_assignment PIN_B11 -to hsmc_tx_n[15]
# set_location_assignment PIN_B13 -to hsmc_tx_p[16]
# set_location_assignment PIN_A13 -to hsmc_tx_n[16]
#
# set_location_assignment PIN_C10 -to hsmc_d[0]
# set_location_assignment PIN_C9 -to hsmc_d[2]
# set_location_assignment PIN_H13 -to hsmc_d[1]
# set_location_assignment PIN_H12 -to hsmc_d[3]
#
# set_location_assignment PIN_AA28 -to hsmc_scl
# set_location_assignment PIN_AE29 -to hsmc_sda



	# Commit assignments
	export_assignments

