#!/bin/sh

# TCL Template Filename
TCL_TEMP_FILE=../../zynqmp_bp.tcl.in

# The fpga device we are building for
FPGA_DEVICE=xczu3eg-sfvc784-1-e
FPGA_DEV_SHORT=xczu3eg

# Base Project Name
BOARD_NAME=fz3
PRJ_NAME="$BOARD_NAME"_"$FPGA_DEV_SHORT"

# The board part file url, if the target has one
BOARD_PART="myirtech.com:fz3:part0:1.0"

# The physical package pin constraint file
PIN_HW_XDC_FILE=const/fz3_pinmap.xdc

# The filename of the top level block diagram
TOP_LEVEL_BD_FILE=scripts/soc_system.tcl

## HostMot2 Pin constraints - these update the IP. Physical pin constraints
#  belong in an xdc file above

# HM2 Pin Filename relative to project folder
PIN_FILE=const/PIN_FZ3_36.vhd
# Pin package name defined in above pin file
PIN_NAME=PIN_FZ3_36
#FWID File name in the const folder
FWID_NAME=FWID_FZ3_36

############################################################################
# HostMot2 Generic Parameters, autofills IP correctly without regenerating
# block diagram script
############################################################################

# The name of the board to compile into the IP. Matches board name in hal files
BOARD_NAME_HIGH_HEX=5F335A46    #FZ3_
BOARD_NAME_LOW_HEX=5249594D     #MYIR
