#!/bin/sh

# The top level tcl for this project, relative to this config file
BUILD_TCL=scripts/zturn_ztio_bp.tcl

# The name of the bitfile
BIT_FILE=zturn_ztio.bit

## HostMot2 Pin constraints - these update the IP. Physical pin constraints
#  belong in an xdc file referenced by the tcl scripts.
##

# Pin File relative to HW directory
PIN_FILE=VivadoProjects/zturn/zturn_ztio/const/PIN_ZTIO_34.vhd
# Pin package name defined in above pin file
PIN_NAME=PIN_ZTIO_34
#FWID File name in the const folder
FWID_NAME=FWID_ZTIO_34

############################################################################
# HostMot2 Generic Parameters, autofills IP correctly without regenerating
# block diagram script
############################################################################

# The name of the board to compile into the IP. Matches board name in hal files
BOARD_NAME_HIGH_HEX=4F49545A    #ZTIO
BOARD_NAME_LOW_HEX=5249594D     #MYIR
