#!/bin/sh

# The top level tcl for this project, relative to this config file
BUILD_TCL=scripts/zturn_iocape_bp.tcl

# The name of the bitfile
BIT_FILE=zturn_iocape.bit

# The name of the board to compile into the IP. Matches board name in hal files
BOARD_NAME_HEX=5A54494F     #ZTIO

## HostMot2 Pin constraints - these update the IP. Physical pin constraints
#  belong in an xdc file referenced by the tcl scripts.
##

# Pin File relative to HW directory
PIN_FILE=VivadoProjects/zturn/zturn_iocape/const/PIN_ZTURNIOCAPE_34.vhd
# Pin package name defined in above pin file
PIN_NAME=PIN_ZTURNIOCAPE_34
