#!/bin/sh

# The top level tcl for this project, relative to this config file
BUILD_TCL=scripts/microzed_jd2cb_bp.tcl

# The name of the bitfile
BIT_FILE=microzed_jd2cb.bit

# The name of the board to compile into the IP. Matches board name in hal files
BOARD_NAME_HEX=4243444A     #JDCB 

## HostMot2 Pin constraints - these update the IP. Physical pin constraints
#  belong in an xdc file referenced by the tcl scripts.
## 

# Pin File relative to HW directory
PIN_FILE=VivadoProjects/microzed/microzed_jd2cb/const/PIN_JD2CB_34.vhd
# Pin package name defined in above pin file
PIN_NAME=PIN_JD2CB_34

